// This file is generated. Do not edit by hand.
// Canonical token input SHA-256: defb411c1dc94b1071a70bc92dfa7eff0c7ab443fc110dd86c1cfbd8f54182f4
// Canonical #AARRGGBB colours are emitted as React Native #RRGGBBAA.

export const seatLayerPickerTokenSourceSha256 = 'defb411c1dc94b1071a70bc92dfa7eff0c7ab443fc110dd86c1cfbd8f54182f4' as const;
export const seatLayerPickerTokenVersion = 1 as const;

export const seatLayerPickerTokens = {
  "color": {
    "dark": {
      "accent": "#9B8AFB",
      "background": "#0F1522",
      "chrome": "#556278",
      "chromeLine": "#E9EEF78C",
      "divider": "#A5AEC23D",
      "error": "#FF6B6B",
      "immersiveCaption": "#0A0E16D1",
      "immersiveCaptionBorder": "#FFFFFF33",
      "immersiveCaptionInk": "#EEF3FB",
      "immersiveGlass": "#0A0E149E",
      "immersiveGlassBorder": "#FFFFFF38",
      "immersiveGlassInk": "#E6EDF3",
      "mapBackground": "#0F1522",
      "mapRowLabel": "#D7DEEA",
      "mapSelection": "#9B8AFB",
      "mapText": "#F4F7FB",
      "mutedText": "#A5AEC2",
      "onAccent": "#110D20",
      "premium": "#E8C15A",
      "premiumText": "#DCCBA5",
      "surface": "#1A2234",
      "text": "#EEF1F8",
      "warnText": "#E3CC93",
      "warning": "#F4B740"
    },
    "light": {
      "accent": "#5B4B8A",
      "background": "#FFFFFF",
      "chrome": "#d6dce6",
      "chromeLine": "#1720338C",
      "divider": "#17203329",
      "error": "#B42318",
      "mapBackground": "#E9EDF4",
      "mapRowLabel": "#334155",
      "mapSelection": "#5B4B8A",
      "mapText": "#172033",
      "mutedText": "#667085",
      "onAccent": "#FFFFFF",
      "premium": "#E8C15A",
      "premiumText": "#6C5E3F",
      "surface": "#F6F7FB",
      "text": "#172033",
      "warnText": "#745F2C",
      "warning": "#F4B740"
    }
  },
  "elevation": {
    "confirmCard": 18,
    "dockBar": 8,
    "header": 0,
    "pill": 0,
    "sheet": 12
  },
  "haptics": {
    "cardArrived": "light",
    "cardCancelled": "selection",
    "holdCreated": "medium",
    "holdEnding": "warning",
    "holdExpired": "heavy",
    "note": "The first snapshot of a session never fires a cue: a resumed focus or hold is not something the buyer just did.",
    "seatConfirmed": "medium",
    "sectionFocused": "selection",
    "selectionAdded": "selection",
    "ticketRemoved": "light"
  },
  "motion": {
    "budgetMs": 420,
    "curve": {
      "easeEnter": {
        "cubicBezier": [
          0.2,
          0.8,
          0.2,
          1
        ],
        "name": "cubic"
      },
      "easeExit": {
        "cubicBezier": [
          0.4,
          0,
          1,
          1
        ],
        "name": "cubic"
      },
      "spring": {
        "cubicBezier": [
          0.34,
          1.56,
          0.64,
          1
        ],
        "name": "cubic"
      }
    },
    "duration": {
      "bump": 240,
      "cardEnter": 240,
      "chevron": 240,
      "crossfade": 120,
      "dock": 240,
      "enter": 260,
      "exit": 180,
      "fly": 420,
      "immersive": 300,
      "pop": 180,
      "pressSweep": 360,
      "sheet": 300,
      "stagger": 60,
      "thumbOut": 160,
      "toast": 200
    },
    "durationOutsideBudget": {
      "confirmFlight": 500,
      "inviteBreathe": 2400,
      "inviteBreatheDelay": 1000,
      "inviteDelay": 300,
      "inviteSweep": 700,
      "revealDelay": 900,
      "shellSweep": 650,
      "toastDwell": 4200,
      "undoWindow": 4000
    },
    "physics": {
      "note": "Native-only. A finger on glass is answered by a simulation, not by a fixed-duration tween: the sheet and a swiped row settle from wherever the finger left them, at the speed the finger left them at.",
      "rubberBand": 0.35,
      "sheetFlingVelocity": 320,
      "sheetSpringDamping": 34,
      "sheetSpringMass": 1,
      "sheetSpringStiffness": 420,
      "swipeCommitFraction": 0.4,
      "swipeFlingVelocity": 700
    },
    "reducedMotion": "Every duration collapses to 0 ms when the viewer asks for less movement; motion with no reduced form (fly-to-tray, staggered arrival) is skipped rather than played instantly."
  },
  "opacity": {
    "confirmScrim": 0.38,
    "confirmScrimFlat": 0.5,
    "mapControlDisabled": 0.42,
    "noteBodyInk": 0.75,
    "noteHairline": 0.6,
    "noteNeutralWash": 0.06,
    "noteToneWash": 0.1,
    "removing": 0.45,
    "warnPillWash": 0.18
  },
  "radius": {
    "base": 14,
    "button": 9,
    "card": 18,
    "chip": 999,
    "confirmCard": 15,
    "control": 9,
    "headerLogo": 6,
    "peekButton": 12,
    "pill": 999,
    "sheet": 14,
    "smallRatio": 0.55
  },
  "size": {
    "accessNoteIconSize": 15,
    "accessRowGap": 10,
    "accessRowIconCell": 20,
    "accessRowIconSize": 17,
    "accessRowLabelFontSize": 12.5,
    "accessRowNoteFontSize": 10.5,
    "accessRowPaddingX": 8,
    "accessRowPaddingY": 6,
    "accessRowSwitchGap": 12,
    "accessSheetMaxHeightFraction": 0.72,
    "accessSheetMinHeight": 240,
    "accessStepFontSize": 11,
    "accessStepGap": 5,
    "accessStepHeight": 30,
    "accessStepPaddingX": 9,
    "accessSwitchHeight": 20,
    "accessSwitchKnob": 16,
    "accessSwitchWidth": 34,
    "accessibilityControlSize": 36,
    "attributionHeight": 18,
    "bestSeatsSelectHeight": 34,
    "bestSeatsStepperWidth": 112,
    "cartCardGap": 6,
    "cartCardMinHeight": 52,
    "cartCardRadius": 12,
    "cartNoteGap": 3,
    "cartNotePadTop": 5,
    "cartPeekMaxHeight": 189,
    "cartTrayPadBottom": 2,
    "cartTrayPadTop": 10,
    "cartTrayPadX": 14,
    "checkoutButtonHeight": 44,
    "confidenceTeaserBadgeFont": 11,
    "confidenceTeaserDetailFont": 9.5,
    "confidenceTeaserHeadFont": 11,
    "confidenceTeaserMinHeight": 44,
    "confidenceTeaserPadX": 10,
    "confidenceTeaserPadY": 8,
    "confidenceTeaserRadius": 9,
    "confidenceTeaserTop": 8,
    "confirm3dSquareFontSize": 9.5,
    "confirmActionHeight": 44,
    "confirmBandHeight": 30,
    "confirmBandNameFontSize": 15,
    "confirmBandPadBottom": 11,
    "confirmBandPadLeading": 14,
    "confirmBandPadTop": 11,
    "confirmBandPadTrailing": 16,
    "confirmBandPriceFontSize": 18,
    "confirmCardClearance": 18,
    "confirmCardGutter": 12,
    "confirmCardImmersiveMaxWidth": 342,
    "confirmCardImmersiveRestInset": 10,
    "confirmCardMaxWidth": 310,
    "confirmCardRestInset": 14,
    "confirmCardSeatGap": 12,
    "confirmCardTopInset": 12,
    "confirmIdentityHeight": 42,
    "confirmIdentityKeyFontSize": 9,
    "confirmIdentityLongSectionFontSize": 12.5,
    "confirmIdentityValueFontSize": 18,
    "confirmImmersiveActionGap": 7,
    "confirmImmersiveBandPadX": 10,
    "confirmImmersiveBandPadY": 7,
    "confirmImmersiveBandPriceFontSize": 17,
    "confirmImmersiveBodyBottom": 9,
    "confirmImmersiveBodyTop": 8,
    "confirmImmersiveCellBottom": 7,
    "confirmImmersiveCellSide": 9,
    "confirmImmersiveCellTop": 8,
    "confirmImmersiveInspectGap": 9,
    "confirmImmersiveSectionFontSize": 12,
    "confirmImmersiveValueFontSize": 17,
    "confirmInspectChipFontSize": 11.5,
    "confirmInspectChipHeight": 40,
    "confirmPhotoHeight": 64,
    "confirmPillHeight": 28,
    "confirmRailHeight": 44,
    "confirmScrimBlur": 4,
    "confirmScrimClearRadius": 56,
    "confirmScrimFeatherRadius": 88,
    "confirmSectionShortMax": 6,
    "confirmSightFont": 10,
    "confirmSightPadX": 8,
    "confirmSightPadY": 3,
    "confirmTierHeight": 38,
    "dockBackChevronSize": 18,
    "dockBackFontSize": 12.5,
    "dockBackHeight": 36,
    "dockBarHeight": 52,
    "dockCountFontSize": 12.5,
    "dockDotSize": 10,
    "dockLeadingInset": 14,
    "dockNameFontSize": 12.5,
    "dockNavGap": 2,
    "dockNavHeight": 36,
    "dockNavIconSize": 18,
    "dockNavWidth": 34,
    "dockTrailingInset": 8,
    "emptyTrayMaxHeight": 380,
    "emptyTrayMaxHeightFraction": 0.64,
    "findPillHeight": 48,
    "floorChipFontSize": 10.5,
    "floorChipHeight": 28,
    "floorChipPaddingX": 10,
    "floorInfoSize": 26,
    "floorRailGap": 1,
    "floorRailPadding": 3,
    "footPadBottom": 2,
    "footPadTop": 4,
    "footPadX": 16,
    "footTotalGap": 8,
    "headerCloseSize": 26,
    "headerHeight": 38,
    "headerLogoSize": 22,
    "headerNameFontSize": 12.5,
    "immersiveBackFontSize": 11,
    "immersiveBackIconSize": 15,
    "immersiveBackPillHeight": 44,
    "immersiveCaptionBlur": 8,
    "immersiveCaptionFontSize": 11.5,
    "immersiveGlassBlur": 6,
    "immersiveNavChipFontSize": 12.5,
    "immersiveNavChipHeight": 32,
    "immersiveNavChipPaddingX": 12,
    "immersiveNavCloseSize": 32,
    "legendChipDotSize": 7,
    "legendChipFontSize": 11,
    "legendChipHeight": 24,
    "legendRailEdgeFade": 18,
    "mapAnchorGap": 12,
    "mapAnchorInset": 12,
    "mapControlSize": 36,
    "minimumHitTarget": 44,
    "noteCompactIconSize": 15,
    "noteCompactPadLeading": 15,
    "noteCompactPadX": 12,
    "noteCompactPadY": 7,
    "noteIconGap": 9,
    "noteIconSize": 17,
    "notePadX": 14,
    "notePadY": 9,
    "peekButtonHeight": 48,
    "peekClockLift": 8,
    "peekHeight": 58,
    "phoneBreakpoint": 640,
    "selectorHeight": 44,
    "sheetFullHeightFraction": 0.92,
    "sheetGrabberHeight": 4,
    "sheetGrabberInset": 4,
    "sheetGrabberWidth": 35,
    "sheetHandleHeight": 44,
    "sheetHandleOverhang": 22,
    "sheetHandleWidth": 44,
    "sheetHeadHeight": 16,
    "sheetMaxHeight": 480,
    "sheetMaxHeightFraction": 0.72,
    "sheetOpenHeadHeight": 36,
    "sheetToggleOpenSize": 28,
    "sheetToggleSize": 44,
    "testChipDotSize": 7,
    "testChipFontSize": 11,
    "testChipHeight": 26,
    "toastCardLift": 232,
    "topRailHeight": 44,
    "viewModeButtonHeight": 28,
    "viewModeButtonMinWidth": 38,
    "viewModeControlHeight": 36,
    "viewModeLabelFontSize": 9.5,
    "wideBreakpoint": 840,
    "zoomColumnGap": 6
  },
  "strings": {
    "aboutBestSeats": "About finding seats together",
    "accessCart": "Mobility cart",
    "accessCompanion": "Companion",
    "accessDesignatedAisle": "Aisle seat",
    "accessExpiredCopy": "Reload the seat map to continue. Seats already in your cart stay held until the timer ends.",
    "accessExpiredTitle": "Your seat session has expired",
    "accessFreeCount": "{count} free",
    "accessHearing": "Hearing support",
    "accessJumpFirstSection": "Jump to the first section",
    "accessJumpNextSection": "Jump to the next section",
    "accessLiftArmrest": "Lift armrest",
    "accessLowVision": "Low vision",
    "accessNeedWithCount": "{need} · {count}",
    "accessPausedCopy": "The organizer has paused this selection. Try again in a few minutes.",
    "accessPausedTitle": "These seats are on hold right now",
    "accessPlusSize": "Plus-size seat",
    "accessRefresh": "Refresh",
    "accessRevokedCopy": "Ask whoever sent you here for a new link to keep booking these seats.",
    "accessRevokedTitle": "This access link is no longer active",
    "accessSemiAmbulatory": "Semi-ambulatory",
    "accessSensoryFriendly": "Sensory-friendly",
    "accessSignLanguage": "Sign language view",
    "accessStepFree": "Step-free",
    "accessUnverifiedCopy": "You can still book anything shown as available. Contact whoever sent you here for access to the rest.",
    "accessUnverifiedTitle": "We couldn't verify your access",
    "accessWheelchair": "Wheelchair",
    "accessibility": "Accessibility and view filters",
    "accessibilityTitle": "Accessibility and view",
    "accessiblePhysicalSeat": "Accessible physical seat",
    "accessibleSections": "{count} sections",
    "accessibleStep": "{index} of {total}",
    "addMinutes": "+{count} min",
    "addSeat": "Add seat",
    "addTickets": "Add tickets",
    "addTime": "Add time",
    "added": "Added",
    "addingEllipsis": "Adding…",
    "adjustSelection": "Adjust your selection",
    "allFloors": "All floors",
    "allPrices": "All prices",
    "allSetTitle": "You're all set",
    "anyTicketType": "Any ticket type",
    "anyVenueZone": "Any venue zone",
    "backToMap": "Back to map",
    "backToVenue": "Back to venue",
    "bestSeats": "Best seats",
    "cancel": "Cancel",
    "checkConnection": "Check your connection and try again.",
    "chooseGuestsCopy": "Choose how many guests will sit together. This table is held exclusively for your party.",
    "chooseMinMaxGuests": "Choose between {min} and {max} guests.",
    "chooseMore": "Choose {count} more",
    "chooseSeats": "Choose your seats",
    "chooseTableGuests": "Choose the number of guests for this table",
    "chooseTickets": "Choose tickets",
    "close": "Close seat selection",
    "closestGroupChosenInstantly": "Closest available group, chosen instantly.",
    "collapseCart": "Collapse ticket panel",
    "colorblindSafe": "Colourblind-friendly colours",
    "companionSeatsNote": "Companion places beside them stay selectable",
    "confirmOrCancelSeat": "Confirm or cancel this seat",
    "confirmTable": "Confirm table",
    "confirmYourTickets": "Confirm your tickets",
    "confirmedAndOnWay": "confirmed. A confirmation is on its way.",
    "continueToCheckout": "Continue to checkout",
    "continueWithTotal": "Continue · {money}",
    "continueWord": "Continue",
    "couldNotAddMoreTime": "Couldn't add more time — please head to checkout now.",
    "displayOptions": "Display options",
    "emptyTrayHint": "Tap a seat on the map, or let us pick the best available for you.",
    "emptyWheelchairSpace": "Empty wheelchair space",
    "errorMessage": "The seat map could not be loaded.",
    "expandCart": "Open ticket panel",
    "fewerGuests": "Fewer guests",
    "fewerTickets": "Fewer tickets",
    "findBestSeats": "Find {count} best seats",
    "findBestSeatsCta": "Find best seats",
    "findBestSeatsOne": "Find {count} best seat",
    "findBestSeatsOther": "Find {count} best seats",
    "findSeats": "Find seats",
    "findSeatsTogether": "Find seats together",
    "findingBestSeats": "Finding the best seats…",
    "fitVenue": "Fit venue",
    "fitWholeVenue": "Show whole venue",
    "flat2dMap": "Flat 2D map",
    "fromPrice": "From {price}",
    "generalAdmission": "General admission",
    "heldFor": "{clock}",
    "hideLimitedView": "Hide limited-view seats",
    "holdAlreadyHeldBody": "Continue to checkout to keep them.",
    "holdAlreadyHeldTitle": "Your seats are already held",
    "holdAndCheckout": "Hold seats & checkout",
    "holdExpired": "Your hold expired — the seats were released. Pick again.",
    "holdInCheckoutBody": "Finish checkout to keep them. To pick different seats, release these first — they go back on sale.",
    "holdInCheckoutTitle": "Your seats are already in checkout",
    "holdLapsedAllTakenOne": "Your hold ended while you were away, and that seat has been taken.",
    "holdLapsedAllTakenOther": "Your hold ended while you were away, and those seats have been taken.",
    "holdLapsedBody": "They were held for {n} minutes.",
    "holdLapsedSomeTakenOne": "Your hold ended while you were away, and {count} of those seats has been taken. The rest are still free.",
    "holdLapsedSomeTakenOther": "Your hold ended while you were away, and {count} of those seats have been taken. The rest are still free.",
    "holdLapsedStillFreeOne": "Your hold ended while you were away. That seat is still free.",
    "holdLapsedStillFreeOther": "Your hold ended while you were away. Those seats are still free.",
    "holdLapsedTitle": "Your seats were released.",
    "holdMinutesLeftOne": "{count} minute left",
    "holdMinutesLeftOther": "{count} minutes left",
    "holdSecondsLeftOne": "{count} second left",
    "holdSecondsLeftOther": "{count} seconds left",
    "interactive3dVenueView": "Interactive 3D venue view",
    "loading": "Loading seat map…",
    "mapDidNotLoad": "The seat map didn't load",
    "mapView": "Map",
    "moreCount": "+{count} more",
    "moreGuests": "More guests",
    "moreTickets": "More tickets",
    "moreTimeAdded": "More time added — your seats are still held.",
    "moveVenue": "Drag to move venue",
    "nextSeat": "Next seat",
    "nextSection": "Next section",
    "noSeatsSelected": "No seats selected",
    "noSelectableSeats": "No selectable seats are currently available.",
    "notAvailable": "Not available",
    "numberOfGuests": "Number of guests",
    "obstructedView": "Obstructed view",
    "onlyLeft": "Only {count} left",
    "openVenue360": "Open venue 360°",
    "openingCheckout": "Opening secure checkout…",
    "orbitMode": "Rotate venue",
    "organizerNote": "Organizer note",
    "overview": "Venue",
    "panMode": "Move venue",
    "passport": "Passport",
    "peekSecured": "✓ {count} secured · {total} — you won't be charged yet",
    "pickYourSeats": "Pick your seats",
    "placeNumberIdentity": "Place {place}",
    "placeWord": "Place",
    "placesAvailable": "{count} places currently available",
    "poweredBy": "Powered by SeatLayer",
    "premiumSeat": "Premium seat",
    "previousSeat": "Previous seat",
    "previousSection": "Previous section",
    "recentre": "Recentre the view",
    "releaseAndChangeSeats": "Release and change seats",
    "reloadSeatMap": "Reload seat map",
    "removeSeat": "Remove seat",
    "removeTickets": "Remove {count} tickets",
    "removeTicketsOne": "Remove {count} ticket",
    "removeTicketsOther": "Remove {count} tickets",
    "removeWord": "Remove",
    "reselectSeats": "Select them again",
    "reselectSeatsOne": "Select it again",
    "reselectSeatsOther": "Select them again",
    "restrictedView": "Restricted view",
    "retry": "Try again",
    "rotateVenue": "Drag to rotate venue",
    "rowIdentity": "Row {row}",
    "rowWord": "Row",
    "salesClosed": "Sales are closed",
    "salesClosedCopy": "Ticket sales for this event have ended.",
    "salesClosedCta": "Sales closed",
    "salesClosedPill": "Sales are closed",
    "salesClosedToast": "Sales are closed for this event.",
    "seatIdentity": "{parts}",
    "seatJustTakenByAnother": "Seat {label} was just taken by another buyer.",
    "seatNumberIdentity": "Seat {seat}",
    "seatRemoved": "Ticket removed",
    "seatWord": "Seat",
    "seatsFree": "{count} seats",
    "seatsFreeOne": "{count} seat",
    "seatsFreeOther": "{count} seats",
    "seatsHeldForNeedMoreTime": "Your seats are held for {time}. Need more time?",
    "seatsJustTaken": "One or more seats were just taken. Please pick again.",
    "seatsLeft": "{count} left",
    "seatsLeftInSectionOne": "{count} seat left",
    "seatsLeftInSectionOther": "{count} seats left",
    "seatsNotRecovered": "{n} could not be recovered",
    "seatsSecuredOpeningCheckout": "Seats secured. Opening checkout…",
    "sectionWord": "Section",
    "secureMore": "Secure more",
    "secureMoreAndCheckout": "Secure {count} more & checkout",
    "securingSeats": "Securing your seats…",
    "seeItIn3D": "See it in 3D",
    "select": "Select",
    "selectSeats": "Select seats",
    "selectTable": "Select table",
    "selectTicketTier": "Select a ticket type",
    "showLess": "Show less",
    "sightline": "≈ {m} m to stage",
    "soldOutCopy": "No reserved seats are currently available for this event.",
    "soldOutEyebrow": "This event",
    "soldOutTitle": "Sold out",
    "testMode": "Test mode",
    "testModeExplained": "Bookings here are not real and no card is charged",
    "testModeLong": "Test mode · books nothing",
    "ticketCount": "{count} tickets",
    "ticketCountOne": "{count} ticket",
    "ticketCountOther": "{count} tickets",
    "ticketType": "Ticket type",
    "tierCompanionGuidance": "Requires the adjacent wheelchair place.",
    "undo": "Undo",
    "updateTable": "Update table",
    "venue3D": "3D",
    "venueMap": "{venue} seat map",
    "venueMapHint": "Seats are picked with the controls around the map: the price rail above it, the section controls below it, and the ticket panel at the foot.",
    "venueView": "Venue view",
    "venueZone": "Venue zone",
    "viewFromHere": "View from here",
    "viewFromThisSeat": "View from this seat",
    "viewFromYourSeat": "view from your seat",
    "viewGroupTitle": "VIEW",
    "zoomIn": "Zoom in",
    "zoomOut": "Zoom out"
  },
  "type": {
    "accessStep": {
      "size": 11,
      "weight": 800
    },
    "attribution": {
      "size": 11,
      "weight": 600
    },
    "bestSeatsGo": {
      "size": 12.5,
      "weight": 800
    },
    "bestSeatsSelect": {
      "size": 12.5,
      "weight": 700
    },
    "bookButton": {
      "size": 14,
      "weight": 800
    },
    "cartCardAmount": {
      "size": 15,
      "weight": 800
    },
    "cartCardName": {
      "size": 15,
      "weight": 700
    },
    "cartCardPosition": {
      "size": 13,
      "weight": 600
    },
    "cartNoteText": {
      "size": 10,
      "weight": 600
    },
    "cartNoteTitle": {
      "size": 10,
      "weight": 800
    },
    "confirmAction": {
      "size": 14,
      "weight": 800
    },
    "confirmIdentity": {
      "size": 14,
      "weight": 800
    },
    "dockCount": {
      "size": 13,
      "weight": 600
    },
    "dockSection": {
      "size": 14,
      "weight": 800
    },
    "findPill": {
      "size": 16,
      "weight": 800
    },
    "footTotalAmount": {
      "size": 17,
      "weight": 700
    },
    "footTotalLabel": {
      "size": 13,
      "weight": 600
    },
    "headerTitle": {
      "size": 16,
      "weight": 800
    },
    "legendChip": {
      "size": 11,
      "weight": 800
    },
    "noteBody": {
      "size": 11,
      "weight": 400
    },
    "noteBodyCompact": {
      "size": 10.5,
      "weight": 400
    },
    "noteTitle": {
      "size": 12.5,
      "weight": 800
    },
    "noteTitleCompact": {
      "size": 11.5,
      "weight": 750
    },
    "peekFromPrice": {
      "size": 19,
      "weight": 850
    },
    "peekPill": {
      "size": 16,
      "weight": 800
    },
    "peekSummary": {
      "size": 12,
      "weight": 700
    },
    "peekSummaryOpen": {
      "size": 14,
      "weight": 700
    },
    "pill": {
      "size": 12,
      "weight": 800
    },
    "scaleClamp": {
      "card": 1.3,
      "dock": 1.3,
      "note": "How far a surface lets the platform's text-size setting grow its type before its layout would break. Prompts and dialogs are deliberately absent: they own the screen, scroll, and are never clamped.",
      "peek": 1.3,
      "rail": 1.3,
      "sheet": 1.6,
      "state": 1.6
    }
  },
  "version": 1
} as const;

export type SeatLayerPickerGeneratedTokens = typeof seatLayerPickerTokens;
